Vagrant.configure("2") do |config|
	
  config.vm.define "web_1" do |web_1|
      web.vm.box = "ubuntu/xenial64"
	  config.vm.provider :virtualbox do |vb|
			vb.customize [ 'modifyvm', :id, '--name', 'demo-00' ]
		 vb.customize [ 'modifyvm', :id, '--cpus', 1 ]
		vb.customize [ 'modifyvm', :id, '--memory', 720 ]
		vb.customize [ 'modifyvm', :id, '--cpuexecutioncap', 50 ] 

	 end
	config.vm.provision "shell", path: "script.sh"

	config.vm.network "forwarded_port", guest: 80, host: 8080
	config.vm.synced_folder "./www_1" , "/var/www_1/html"
	  
	  
  end
	
	
	
  config.vm.define "web_2" do |web_2|
      db.vm.box = "ubuntu/xenial64"
	   config.vm.provider :virtualbox do |vb|
			vb.customize [ 'modifyvm', :id, '--name', 'demo-00' ]
		 vb.customize [ 'modifyvm', :id, '--cpus', 1 ]
		vb.customize [ 'modifyvm', :id, '--memory', 720 ]
		vb.customize [ 'modifyvm', :id, '--cpuexecutioncap', 50 ] 

	 end
	config.vm.provision "shell", path: "script.sh"

	config.vm.network "forwarded_port", guest: 80, host: 8008
	config.vm.synced_folder "./www_2" , "/var/www_2/html"
	  
	  
	  
  end
end






Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provider :virtualbox do |vb|
	vb.customize [ 'modifyvm', :id, '--name', 'demo-00' ]
 vb.customize [ 'modifyvm', :id, '--cpus', 1 ]
vb.customize [ 'modifyvm', :id, '--memory', 720 ]
vb.customize [ 'modifyvm', :id, '--cpuexecutioncap', 50 ] 

 end
config.vm.provision "shell", path: "script.sh"

config.vm.network "forwarded_port", guest: 80, host: 8080
config.vm.synced_folder "./www" , "/var/www/html"
end
